application {
  mainClass = 'dev.braintrust.examples.ApiClientExample'
}

dependencies {
  implementation project(':braintrust-api')
  implementation "com.fasterxml.jackson.core:jackson-databind:${rootProject.ext.jacksonVersion}"
}

run {
  description = 'Read various api resources via the low-level API client. This also includes example for Create/Update/Delete, but these mutating operations are intentionally not invoked by default.'
}
